### ISSUE TITLE
Search PATH for VFSForGit-enabled Git binary

### ISSUE THREAD

**Issue by chrisd8088** [github/VFSForGit#10]
Instead of expecting our VFSForGit-enabled `git` binary to be installed in `/usr/local/bin`, as per the [macOS implementation](https://github.com/github/VFSForGit/blob/features/linuxprototype/GVFS/GVFS.Platform.Mac/MacGitInstallation.cs#L20), we should look through the locations in our `PATH` environment variable and check for a `git` whose version matches the one we need, or fail if the first found one does not.

We should be able to use [Environment.GetEnvironmentVariable()](https://docs.microsoft.com/en-us/dotnet/api/system.environment.getenvironmentvariable?view=netframework-4.7.2#System_Environment_GetEnvironmentVariable_System_String_) to acquire the `PATH` variable, at least.

**Comment by chrisd8088** [comment]
Some additional valuable suggestions from @bk2204, regarding how we could use Git config extensions:

> Git 2.7.0 and newer have support for an `extensions` section in the config. If you set `core.repositoryFormatVersion` to `1`, then you can set extensions, and if the git binary in question doesn’t understand them, it will abort. Therefore, for VFS for Git repositories, it’s possible to simply create your own extension, say, `extensions.vfsforgit`, and set it to `1` in the repository config file. A suitably enabled Git will know about it, but if there’s a different Git on the system that isn’t capable of that, it will fail in a noisy way, making it obvious what’s going on. libgit2 should also fail here, which we’d want as well.
> 
> That doesn’t solve the problem of finding the right Git, but it does ensure that if we use `PATH`, we don’t have to worry as much that we accidentally have the wrong Git. We won’t, for example, have to worry about data corruption.

**Comment by kivikakk** [comment]
`which`-based solution at https://github.com/Microsoft/VFSForGit/pull/999.
