### ISSUE TITLE
Determine top-level projection state and pass to libprojfs at mount time

### ISSUE THREAD

**Issue by chrisd8088** [github/VFSForGit#20]
See details in github/libprojfs#71, particularly:

> To determine the value of this flag will be an interesting effort, since we do not want to set it on every `gvfs mount` operation, only the first one.  Two options present themselves:
> 1. Perform a call to `StartVirtualizationInstance()` at the end of `gvfs clone`, perhaps in the [`TryPrepareFolderForCallbacks()`](https://github.com/github/VFSForGit/blob/54dc07117a1a09a40907a7f738a06b4b9aebaed5/GVFS/GVFS.Platform.Linux/ProjFSLib.cs#L50) method which is run at the very end of the [`CloneVerb`](https://github.com/microsoft/VFSForGit/blob/d93e2685d5106a4d9d826576b3177cb33adb78aa/GVFS/GVFS/CommandLine/CloneVerb.cs#L649) process.
> 2. At the start of the `gvfs mount` process, check whether the `.gvfs/lower` directory contains only `.git` and `.gitattributes`, and if so, set the "initial mount" flag to the [`StartVirtualizationInstance()`](https://github.com/github/VFSForGit/blob/54dc07117a1a09a40907a7f738a06b4b9aebaed5/GVFS/GVFS.Platform.Linux/LinuxFileSystemVirtualizer.cs#L227) call.

> I am personally inclined toward the second option, as it effectively lifts the "is this directory empty" logic up to the client program's level, where it can determine if the directory is empty according to its own rules (in this case, if it only has the expected post-clone contents), and because it should avoid the need for a full mount/unmount cycle at the end of the cloning step, which feels like a more fragile solution overall.

**Comment by kivikakk** [comment]
#24 merged.
